spring:
  application:
    name: E-Commerce-mvp
    
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    expiration: ${JWT_EXPIRATION}
